<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>The Company respects your privacy and values the trust you place in it. Set out below is the Company&rsquo;s &lsquo;Privacy Policy&rsquo; which details the manner in which information relating to you is collected, used and disclosed.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>Customer are advised to read and understand our Privacy Policy carefully, as by accessing the website/app you agree to be bound by the terms and conditions of the Privacy Policy and consent to the collection, storage and use of information relating to you as provided herein.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:12.25pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>We are committed to safeguarding the privacy of our website visitors; this policy sets out how we will treat your personal information.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.8pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>If you do not agree with the terms and conditions of our Privacy Policy, including in relation to the manner of collection or use of your information, please do not use or access the website/app.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.25pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>We may collect, store and use the following kinds of personal information</span></strong><strong><span style='font-size:16px;font-family:"Times New Roman","serif";'>:</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:16.1pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:147%;font-family:"Times New Roman","serif";'>1. information about your computer and about your visits to and use of this website (including your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views, website navigation);</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.45pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:145%;font-family:"Times New Roman","serif";'>2. information relating to any transactions carried out between you and us on or in relation to this website, including information relating to any purchases you make of our goods or services;</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.7pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p><span style='font-size:16px;font-family:"Times New Roman","serif";'>information that you provide to us for the purpose of registering and subscribing to our website services, email notifications and/or newsletters ,any other information that you choose to send to us; and other information.</span></p>
<p><br></p>
<p><strong>C</strong><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>hoices</span></strong><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>&nbsp;Available Regarding Collection, Use and Distribution of Information</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:15.5pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>To protect against &nbsp;the loss, misuse and alteration of the information under its control, the</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>Company has in place appropriate physical, electronic and managerial procedures. For example,</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>the Company servers are accessible only to authorized personnel and your information is shared</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>with employees and authorized personnel on a need to know basis to complete the transaction</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>and to provide the services requested by you. Although the Company endeavors to safeguard the</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.85pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>confidentiality of your personally identifiable information, transmissions made by means of the</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>Internet cannot be made absolutely secure. By using the website, you agree that the Company</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>will have no liability for disclosure of your information due to errors in transmission and/or</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>unauthorized acts of third parties.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.25pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>Please note that the Company will not ask you to share any sensitive data or information via</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>email &nbsp;or &nbsp;telephone. &nbsp;If &nbsp;you &nbsp;receive &nbsp;any &nbsp;such &nbsp;request &nbsp;by &nbsp;email &nbsp;or &nbsp;telephone, &nbsp;please &nbsp;do &nbsp;not</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>respond/divulge any sensitive data or information and forward the information relating to the</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>same for necessary action.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.5pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Cookies</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:12.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>A cookie consists of information sent by a web server to a web browser, and stored by the browser. The information is then sent back to the server each time the browser requests a page from the server. This enables the web server to identify and track the web browser.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>We may use both &ldquo;session&rdquo; cookies and &ldquo;persistent&rdquo; cookies on the website. We will use the session cookies to: keep track of you whilst you navigate the website. We will use the persistent cookies to: enable our website to recognize you when you visit.</span></p>
<p>Session cookies will be deleted from your computer when you close your browser. Persistent</p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>cookies will remain stored on your computer until deleted, or until they reach a specified expiry</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>date.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:13.85pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>We use Google Analytics to analyses the use of this website. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users&#39; computers. The information generated relating to our website is used to create reports about the use of the website. Google will store this information.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Our advertisers/payment services providers may also send you cookies.</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:3.0pt;'><strong><span style='font-size:16px;font-family:"Times New Roman","serif";'>Using your personal information</span></strong><span style='font-size:16px;font-family:"Times New Roman","serif";'>:-</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>Personal information submitted to us via this website will be used for the purposes specified in this privacy policy or in relevant parts of the website.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.25pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>We may use your personal information to:</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.95pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><strong><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>In Device information</span></strong><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>: We may need your device permission to get information about your<strong>&nbsp;</strong>device, like OS (operating system) name, mobile network, hardware model, unique device identifier, etc. Basis these inputs, we intend to optimize your order experience and thereby serving you better</span><span style='font-size:14px;line-height:148%;font-family:"Times New Roman","serif";color:#666666;'>.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.3pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:155%;'><span style='font-size:16px;line-height:155%;font-family:"Times New Roman","serif";'>If you allow us to access your SMS, we read your SMS to autofill or pre-populate &lsquo;OTP&rsquo; while making a transaction and to validate your mobile number. This provides you a seamless purchase experience while making an order and you do not need to move out of the app to read the SMS and then enter it in the app</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:12.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:152%;'><span style='font-size:16px;line-height:152%;font-family:"Times New Roman","serif";'>The app requires access to make phone calls so that you can make phone calls to our customer contact centers directly through the app.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:152%;'><span style='font-size:16px;line-height:152%;font-family:"Times New Roman","serif";'>If you allow us to access your email id then, it enables us to send various deals and offers directly to your email</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:4.7pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>To the extent possible, we provide you the option of not divulging any specific information that you wish for us not to collect, store or use. You may also choose not to use a particular service or feature on the website/application and opt out of any non-essential communications from the Company.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:149%;font-family:"Times New Roman","serif";'>1. Gramango frequently gives out offers to give registered and unregistered members the opportunity to win great discounts and vouchers. Information collected by us for such activities may include contact information and survey questions, which are used to notify contest winners and develop promotions and products respectively. As a member, you will also occasionally receive updates from us about special offers and new products, and in addition, you may look forward to receiving newsletters and exclusive promotions offering special deals. However, you may choose at any time to no longer receive these email messages;</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.3pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:145%;font-family:"Times New Roman","serif";'>2. Provide third parties with statistical information about our users &ndash; but this information will not be used to identify any individual user;</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.7pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:145%;font-family:"Times New Roman","serif";'>3. Deal with enquiries and complaints made by or about you relating to the website and other uses</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>Where you submit personal information for publication on our website, we will publish and otherwise use that information in accordance with the license you grant to us.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.75pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>We will not without your express consent provide your personal information to any third parties for the purpose of direct marketing.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;text-indent:3.0pt;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>All our website financial transactions are handled through our payment services provider, razor pay. We will share information with razor pay only to the extent necessary for the purposes of processing payments you make via our website and dealing with complaints and queries relating to such payments.</span></p>