<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Introduction</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:8.0pt;text-indent:3.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>These terms and conditions gives your use of this website; by using this website, you accept these terms and conditions in full. If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:11.0pt;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>You must be at least 18 years of age to use this website. By using this website and by agreeing to these terms and conditions you warrant and represent that you are at least 18 years of age.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.7pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>This website uses cookies. By using this website and agreeing to these terms and conditions, you consent to our Gramango&#39;s use of cookies in accordance with the terms of Gramango&#39;s privacy policy / cookies policy.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:4.0pt;'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>License to use website</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.95pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:18.0pt;text-indent:3.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>Unless otherwise stated, Gramango and/or its licensors own the intellectual property rights in the website and material on the website. Subject to the license below, all these intellectual property rights are reserved.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:11.0pt;text-indent:3.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>You may view, download for caching purposes only, and print pages or other content from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms and conditions.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.1pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Acceptable use</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:9.0pt;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>You must not use this website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:11.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>You must not use this website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:10.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this website without Gramango written consent.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.95pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>You must not use this website to transmit or send unsolicited commercial communications.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:11.0pt;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>You must not use this website for any purposes related to marketing without Gramango written consent.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Restricted access</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:2.0pt;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>Access to certain areas of this website is restricted, Gramango reserves the right to restrict access to other areas of this website, or indeed this entire website, at Gramango&#39;s discretion.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.75pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:12.0pt;text-align:justify;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>If Gramango provides you with a user ID and password to enable you to access restricted areas of this website or other content or services, you must ensure that the user ID and password are kept confidential.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.55pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:7.0pt;line-height:145%;'><span style='font-size:16px;line-height:145%;font-family:"Times New Roman","serif";'>Gramango may disable your user ID and password in Gramango&#39;s sole discretion without notice or explanation.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:4.0pt;'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>No warranties</span></strong></p>
<p><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'><br>&nbsp;</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:30.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>This website is provided &ldquo;as is&rdquo; without any representations or warranties, express or implied. Gramango makes no representations or warranties in relation to this website or the information and materials provided on this website.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='font-size:16px;font-family:"Times New Roman","serif";'>Without prejudice to the generality of the foregoing paragraph, Gramango does not warrant that:</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <ul style="margin-bottom:0cm;list-style-type: undefined;margin-left:10px;">
        <li style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><span style='line-height:145%;font-family:"Times New Roman","serif";'>this website will be constantly available, or available at all or the information on this website is complete, true, accurate or non-misleading.</span></li>
    </ul>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:15.4pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:1.0pt;text-indent:3.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>Nothing on this website constitutes, or is meant to constitute, advice of any kind. [If you require advice in relation to any [legal, financial or medical] matter you should consult an appropriate professional.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.95pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:16px;font-family:"Times New Roman","serif";'>Severability</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:17.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>If a provision of these terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect. If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.8pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Entire agreement</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:4.0pt;line-height:147%;'><span style='font-size:16px;line-height:147%;font-family:"Times New Roman","serif";'>These terms and conditions, together with documents, constitute the entire agreement between you and Gramango in relation to your use of this website, and supersede all previous agreements in respect of your use of this website.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.05pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>License &amp; Site access</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.1pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:149%;'><span style='font-size:16px;line-height:149%;font-family:"Times New Roman","serif";'>Gramango grants you a limited sub-license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Gramango. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied,&nbsp;</span><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of Gramango. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Site or of Gramango and its affiliates without express written consent.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:6.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Account &amp; Registration Obligations</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:14.5pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>All shoppers have to register and login for placing orders on the Site. You have to keep your account and registration details current and correct for communications related to your purchases from the site. By agreeing to the terms and conditions, the shopper agrees to receive promotional communication and newsletters upon registration.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Pricing</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>All the products listed on the Site will be sold at MRP unless otherwise specified. The prices mentioned at the time of ordering will be the prices charged on the date of the delivery. Although prices of most of the products do not fluctuate on a daily basis. In case the prices are higher or lower on the date of delivery not additional charges will be collected or refunded as the case may be at the time of the delivery of the order.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.3pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Cancellation by Site / Customer</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:8.65pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>You as a customer can cancel your order anytime up to the cut-off time of the slot for which you have placed an order by calling our customer service. In such a case we will refund any payments already made by you for the order. If we suspect any fraudulent transaction by any customer or any transaction which defies the terms &amp; conditions of using the website, we at our sole discretion could cancel such orders. We will maintain a negative list of all fraudulent transactions and customers and would deny access to them or cancel any orders placed by them.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:.7pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Return &amp; Refunds</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>which entitles all our members to return the product at the time of delivery if due to some reason they are not satisfied with the quality or freshness of the product. We will take the returned product back with us and issue a credit note for the value of the return products which will be credited to your account on the Site. This can be used to pay your subsequent shopping bills&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:18.0pt;'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>You Agree and Confirm</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:18.0pt;text-align:justify;line-height:149%;'><span style='font-size:16px;line-height:149%;font-family:"Times New Roman","serif";'>That you will use the services provided by the Site, its affiliates, consultants and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using and transacting on the Site, You will provide authentic and true information in all instances where such information is requested of you. Gramango reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), it has the right in its sole discretion to reject the registration and debar you from using the Services and / or other affiliated websites without prior intimation whatsoever. You authorize Gramango to contact you for any transactional purposes related to your order/account. That you are accessing the services available on this Site and transacting at your sole risk and are using your best and prudent judgment before entering into any transaction through this Site, That the address at which delivery of the product ordered by you is to be made will be correct and proper in all respects, That before placing an order you will check the product description carefully. By placing an order for a product you agree to be bound by the conditions of sale included in the item&#39;s description.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.35pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-left:18.0pt;'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>You may not use the Site for any of the following purposes:</span></strong></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:10.0pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:19.15pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span><span style='line-height:145%;font-family:"Times New Roman","serif";'>1. Disseminating any unlawful, harassing, libelous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:1.15pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:1.15pt;'><span style='line-height:145%;font-family:"Times New Roman","serif";'>2. Transmitting material that encourages conduct that constitutes a criminal offence or results in civil &nbsp; &nbsp; &nbsp;liability or otherwise breaches any relevant laws, regulations or code of practice.</span></p>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:.5pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='font-family:"Times New Roman","serif";font-size:12.0pt;'>3. Gaining unauthorized access to other computer systems.</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:6.95pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='font-family:"Times New Roman","serif";font-size:12.0pt;'>4. Interfering with any other person&#39;s use or enjoyment of the Site.</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:6.85pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='font-family:"Times New Roman","serif";font-size:12.0pt;'>5. Breaching any applicable laws;</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:6.95pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='font-family:"Times New Roman","serif";font-size:12.0pt;'>6. Interfering or disrupting networks or web sites connected to the Site.</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:7.45pt;'><span style='font-size:16px;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<div style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'>
    <p><span style='line-height:145%;font-family:"Times New Roman","serif";'>7. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner.</span></p>
    <p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";'><strong><span style='font-size:19px;font-family:"Times New Roman","serif";'>Modification of Terms &amp; Conditions of Service</span></strong></p>
    <p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";line-height:18.45pt;'><span style='font-family:"Times New Roman","serif";'>&nbsp;</span></p>
    <p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";margin-right:11.0pt;text-align:justify;line-height:148%;'><span style='font-size:16px;line-height:148%;font-family:"Times New Roman","serif";'>Gramango may at any time modify the Terms &amp; Conditions of Use of the Website without any prior notification to you. You can access the latest version of these Terms &amp; Conditions at any given time on the Site. You should regularly review the Terms &amp; Conditions on the Site. In the event the modified Terms &amp; Conditions is not acceptable to you, you should discontinue using the Service. However, if you continue to use the Service you shall be deemed to have agreed to accept and abide by the modified Terms &amp; Conditions of Use of this Site.</span></p>
</div>
<p style='margin:0cm;margin-bottom:.0001pt;font-size:13px;font-family:"Calibri","sans-serif";text-align:justify;line-height:149%;'><br></p>